name: Build and Lint and Test and Doc

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper/
            ./gradle/wrapper/gradle-wrapper.jar
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Download Gradle Wrapper JAR
        if: steps.cache-gradle-wrapper.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./gradle/wrapper
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar -o ./gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Diktat Lint
        run: ./gradlew diktatCheck