name: Build, Lint, and Publish Docs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Diktat Lint
        run: ./gradlew diktatCheck

  dokka-docs-and-deploy:
    needs: build-and-lint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Generate Dokka Documentation
        run: ./gradlew dokkaHtml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/dokka'

      - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4